In [1]:
# import libraries
import numpy as np
import torch 
import torch.nn as nn 

In [2]:
#build two models

widenet = nn.Sequential(
    nn.Linear(2,4), #hidden
    nn.Linear(4,3), #output
)

deepnet = nn.Sequential(
    nn.Linear(2,2), #hidden 
    nn.Linear(2,2), #hidden
    nn.Linear(2,3), #output
)

print(widenet)
print( ' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


## Peeking inside the network

In [3]:
#check the parameters
for p in deepnet.named_parameters():
    print(p)
    print('')
    

('0.weight', Parameter containing:
tensor([[-0.0924,  0.0094],
        [-0.2300,  0.1675]], requires_grad=True))

('0.bias', Parameter containing:
tensor([ 0.4284, -0.1653], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.4788,  0.5279],
        [ 0.0040, -0.1886]], requires_grad=True))

('1.bias', Parameter containing:
tensor([-0.2075, -0.3162], requires_grad=True))

('2.weight', Parameter containing:
tensor([[ 0.1668, -0.6118],
        [-0.2182, -0.0079],
        [-0.2790, -0.0460]], requires_grad=True))

('2.bias', Parameter containing:
tensor([0.1164, 0.0744, 0.6388], requires_grad=True))



In [4]:
#Count the number of nodes ( = the number of biases) 

#named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
    if 'bias' in p[0]:
        numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
    if 'bias' in paramName:
        numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)


There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [5]:
# Just parameters
for p in widenet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[-0.5944,  0.2521],
        [ 0.6625, -0.1627],
        [-0.6965, -0.3900],
        [ 0.1128,  0.7063]], requires_grad=True)
 
Parameter containing:
tensor([ 0.3137, -0.4176,  0.0797, -0.2931], requires_grad=True)
 
Parameter containing:
tensor([[ 0.4402, -0.1461, -0.1163,  0.0403],
        [-0.4418, -0.1506,  0.0335,  0.2080],
        [-0.3183,  0.0949, -0.1588,  0.3193]], requires_grad=True)
 
Parameter containing:
tensor([ 0.4626, -0.4994, -0.1925], requires_grad=True)
 


In [6]:
#Count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
    if p.requires_grad:
        print('This piece has %s parameters' %p.numel())
        nparams += p.numel()

print('\n\nTotal of %s parameters' %nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [10]:
#print model info
from torchsummary import summary 
summary(widenet, (1,2))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
