In [1]:
import numpy as np
import torch 
import torch.nn as nn 

## Usando Numpy

In [7]:
# Crear un vector
v = np.array([1, 40, 2, -3])

#Encontrar y reportar el valor minimo y maximo
minval = np.min(v)
maxval = np.max(v)

print('Min, max: %g,%g' %(minval,maxval))

#ahora con argmin/max

minidx = np.argmin(v)
maxidx = np.argmax(v)

print('Min max indices: %g,%g ' %(minidx, maxidx) ), print(' ')

#confirm
print(f'Min val is { v[minidx] }, max val is {v[maxidx]}')

Min, max: -3,40
Min max indices: 3,1 
 
Min val is -3, max val is 40


In [11]:
#Repetir con matrices
M = np.array([[ 0,1,10],
             [20,8,5]
             ])

print(M), print(' ')

#Various minima in the matrix

minvals1 = np.min(M) #minimum from ENTIRE matrix
minvals2 = np.min(M,axis=0) #min from each column across rows
minvals3 = np.min(M,axis=1) #minimum of each row (across columns)

#print them out
print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


## Using PyTorch

In [13]:
#Repeat with matrix
M = torch.tensor( [[0,1,10], [20,8,5] ])
print(M), print(' ')

#Various minima in matrix
min1 = torch.min(M)
min2 = torch.min(M,axis=0)
min3 = torch.min(M,axis=1)

#printss
print(min1), print(' ')
print(min2), print(' ')
print(min2.values), print(' ')
print(min2.indices), print(' ')


tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
 
tensor([0, 1, 5])
 
tensor([0, 0, 1])
 


(None, None)

In [ ]:
.