In [1]:
#imports
import numpy as np 
import torch 

In [2]:
#Generate random nums
np.random.randn(5)

array([-0.64949412,  0.02886167,  0.5526571 , -1.67707991, -0.33756439])

In [4]:
#Metodo viejo
np.random.seed(17)
print(np.random.randn(5))
print(np.random.randn(5))


[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


In [8]:
#Metodo nuevo
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530)

#Prints

print( randseed1.randn(5))
print( randseed2.randn(5))
print( randseed1.randn(5))
print( randseed2.randn(5))
print( np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.13126776 -1.21256024  0.15999085 -0.75522304  0.34989599]


## Ahora en PyTorch

In [9]:
torch.randn(5)

tensor([ 0.6739, -0.1642,  0.6292, -2.2756, -0.0536])

In [14]:
torch.manual_seed(17)
print( torch.randn(5))

#torch seed doesnt spread to numpy
print(np.random.randn(5))

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 1.1191818  -0.98339611  0.24452002 -0.58140974  0.4295639 ]
